"""
Scenario model — a single test case generated by the Scenario Generator.

input_payload is JSONB and mirrors the format that will be sent to the target agent:
  {
    "messages": [{"role": "user", "content": "..."}],
    "tools": [...],
    "context": {...}
  }

tags: stored as a PostgreSQL ARRAY for efficient filtering without a join table.
"""

from __future__ import annotations

import enum
import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import ARRAY, Enum, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from backend.db.models.evaluation_run import EvaluationRun
    from backend.db.models.judgment import Judgment
    from backend.db.models.trace_metadata import TraceMetadata


class ScenarioSeverity(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Scenario(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "scenarios"
    __table_args__ = (
        Index("ix_scenarios_evaluation_run_id", "evaluation_run_id"),
        Index("ix_scenarios_category", "category"),
        Index("ix_scenarios_severity", "severity"),
        Index("ix_scenarios_tags", "tags", postgresql_using="gin"),
    )

    evaluation_run_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("evaluation_runs.id", ondelete="CASCADE"), nullable=False
    )

    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    severity: Mapped[ScenarioSeverity] = mapped_column(
        Enum(ScenarioSeverity, name="scenario_severity_enum"),
        nullable=False,
        default=ScenarioSeverity.MEDIUM,
    )

    input_payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    expected_behavior: Mapped[str] = mapped_column(Text, nullable=False)
    tags: Mapped[list[str]] = mapped_column(
        ARRAY(String(100)), nullable=False, default=list, server_default="{}"
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    evaluation_run: Mapped[EvaluationRun] = relationship(
        "EvaluationRun", back_populates="scenarios"
    )
    traces: Mapped[list[TraceMetadata]] = relationship(
        "TraceMetadata", back_populates="scenario", cascade="all, delete-orphan"
    )
    judgments: Mapped[list[Judgment]] = relationship(
        "Judgment", back_populates="scenario", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Scenario id={self.id} category={self.category!r} severity={self.severity}>"
