"""Add milestone 9 ai operations fields

Revision ID: 0e258e8b9c04
Revises: db25dbfda68e
Create Date: 2026-07-22 00:36:04.988597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e258e8b9c04'
down_revision: Union[str, Sequence[str], None] = 'db25dbfda68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_runs', sa.Column('drift_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('evaluation_runs', sa.Column('embedding_model_version', sa.String(length=100), nullable=True))
    op.add_column('evaluation_runs', sa.Column('is_baseline', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('evaluation_runs', sa.Column('evolution_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_runs', 'evolution_suggestions')
    op.drop_column('evaluation_runs', 'is_baseline')
    op.drop_column('evaluation_runs', 'embedding_model_version')
    op.drop_column('evaluation_runs', 'drift_profile')
    # ### end Alembic commands ###
