"""audit_remediations

Revision ID: 14f34cc264ce
Revises: 8ea70df16ad2
Create Date: 2026-07-21 18:29:33.411615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14f34cc264ce'
down_revision: Union[str, Sequence[str], None] = '8ea70df16ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('auth_config_encrypted', sa.String(length=2048), nullable=True))
    op.drop_column('agent_configs', 'auth_config')
    op.add_column('golden_baselines', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_constraint(op.f('uq_golden_baselines_tenant_agent'), 'golden_baselines', type_='unique')
    op.create_index('ix_scenarios_tags', 'scenarios', ['tags'], unique=False, postgresql_using='gin')
    op.add_column('trace_metadata', sa.Column('storage_key', sa.String(length=2048), nullable=True))
    op.drop_column('trace_metadata', 's3_uri')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_tenant_email', 'users', ['tenant_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_tenant_email', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('trace_metadata', sa.Column('s3_uri', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('trace_metadata', 'storage_key')
    op.drop_index('ix_scenarios_tags', table_name='scenarios', postgresql_using='gin')
    op.create_unique_constraint(op.f('uq_golden_baselines_tenant_agent'), 'golden_baselines', ['tenant_id', 'agent_config_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('golden_baselines', 'is_active')
    op.add_column('agent_configs', sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('agent_configs', 'auth_config_encrypted')
    # ### end Alembic commands ###
