"""initial_schema

Revision ID: 5b07c1569702
Revises: 
Create Date: 2026-07-21 16:48:12.308411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b07c1569702'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_tenants_slug')
    )
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='user_role_enum'), server_default='MEMBER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('agent_configs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connector_type', sa.Enum('REST_API', 'SDK', 'MCP', name='connector_type_enum'), nullable=False),
    sa.Column('endpoint_url', sa.String(length=2048), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tool_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_configs_created_by', 'agent_configs', ['created_by'], unique=False)
    op.create_index('ix_agent_configs_deleted_at', 'agent_configs', ['deleted_at'], unique=False)
    op.create_index('ix_agent_configs_tenant_id', 'agent_configs', ['tenant_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('agent_config_id', sa.Uuid(), nullable=False, comment='RESTRICT prevents deleting an agent that has evaluation history'),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='run_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('run_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_scenarios', sa.Integer(), server_default='0', nullable=False),
    sa.Column('passed_scenarios', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_scenarios', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluation_runs_agent_config_id', 'evaluation_runs', ['agent_config_id'], unique=False)
    op.create_index('ix_evaluation_runs_created_by', 'evaluation_runs', ['created_by'], unique=False)
    op.create_index('ix_evaluation_runs_status', 'evaluation_runs', ['status'], unique=False)
    op.create_index('ix_evaluation_runs_tenant_id', 'evaluation_runs', ['tenant_id'], unique=False)
    op.create_table('golden_baselines',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('agent_config_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_run_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('behavioral_embedding_collection', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_config_id', name='uq_golden_baselines_tenant_agent')
    )
    op.create_index('ix_golden_baselines_agent_config_id', 'golden_baselines', ['agent_config_id'], unique=False)
    op.create_index('ix_golden_baselines_evaluation_run_id', 'golden_baselines', ['evaluation_run_id'], unique=False)
    op.create_index('ix_golden_baselines_tenant_id', 'golden_baselines', ['tenant_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('evaluation_run_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='scenario_severity_enum'), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_behavior', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=100)), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenarios_category', 'scenarios', ['category'], unique=False)
    op.create_index('ix_scenarios_evaluation_run_id', 'scenarios', ['evaluation_run_id'], unique=False)
    op.create_index('ix_scenarios_severity', 'scenarios', ['severity'], unique=False)
    op.create_table('trace_metadata',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_run_id', sa.Uuid(), nullable=False),
    sa.Column('s3_uri', sa.String(length=2048), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'TIMEOUT', name='trace_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trace_metadata_evaluation_run_id', 'trace_metadata', ['evaluation_run_id'], unique=False)
    op.create_index('ix_trace_metadata_scenario_id', 'trace_metadata', ['scenario_id'], unique=False)
    op.create_index('ix_trace_metadata_status', 'trace_metadata', ['status'], unique=False)
    op.create_table('judgments',
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_run_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.Column('correctness_score', sa.Float(), nullable=True),
    sa.Column('instruction_following_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('judge_model', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['trace_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id')
    )
    op.create_index('ix_judgments_evaluation_run_id', 'judgments', ['evaluation_run_id'], unique=False)
    op.create_index('ix_judgments_passed', 'judgments', ['passed'], unique=False)
    op.create_index('ix_judgments_scenario_id', 'judgments', ['scenario_id'], unique=False)
    op.create_index('ix_judgments_trace_id', 'judgments', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_judgments_trace_id', table_name='judgments')
    op.drop_index('ix_judgments_scenario_id', table_name='judgments')
    op.drop_index('ix_judgments_passed', table_name='judgments')
    op.drop_index('ix_judgments_evaluation_run_id', table_name='judgments')
    op.drop_table('judgments')
    op.drop_index('ix_trace_metadata_status', table_name='trace_metadata')
    op.drop_index('ix_trace_metadata_scenario_id', table_name='trace_metadata')
    op.drop_index('ix_trace_metadata_evaluation_run_id', table_name='trace_metadata')
    op.drop_table('trace_metadata')
    op.drop_index('ix_scenarios_severity', table_name='scenarios')
    op.drop_index('ix_scenarios_evaluation_run_id', table_name='scenarios')
    op.drop_index('ix_scenarios_category', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index('ix_golden_baselines_tenant_id', table_name='golden_baselines')
    op.drop_index('ix_golden_baselines_evaluation_run_id', table_name='golden_baselines')
    op.drop_index('ix_golden_baselines_agent_config_id', table_name='golden_baselines')
    op.drop_table('golden_baselines')
    op.drop_index('ix_evaluation_runs_tenant_id', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_status', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_created_by', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_agent_config_id', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('ix_agent_configs_tenant_id', table_name='agent_configs')
    op.drop_index('ix_agent_configs_deleted_at', table_name='agent_configs')
    op.drop_index('ix_agent_configs_created_by', table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
