"""fix_deleted_at_type

Revision ID: 8ea70df16ad2
Revises: 5b07c1569702
Create Date: 2026-07-21 18:01:06.938194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea70df16ad2'
down_revision: Union[str, Sequence[str], None] = '5b07c1569702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # UUID→DateTime cannot be cast in-place. Since this is a fresh schema with
    # no production data, we drop and re-add the column safely.
    op.drop_index('ix_agent_configs_deleted_at', table_name='agent_configs')
    op.drop_column('agent_configs', 'deleted_at')
    op.add_column('agent_configs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_agent_configs_deleted_at', 'agent_configs', ['deleted_at'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_configs', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
