"""Add last_heartbeat_at to EvaluationRun

Revision ID: db25dbfda68e
Revises: 14f34cc264ce
Create Date: 2026-07-21 23:51:56.122279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db25dbfda68e'
down_revision: Union[str, Sequence[str], None] = '14f34cc264ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_configs_tenant_id_fkey'), 'agent_configs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_configs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('evaluation_runs', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_runs', 'last_heartbeat_at')
    op.drop_constraint(None, 'agent_configs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_configs_tenant_id_fkey'), 'agent_configs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
